name: EC-2 push
run-name: ${{ github.actor }} is pushing new code to ec2
on:
    push:
      branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/amma-bot
          remote_host: "${{ secrets.HOST_IP }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
        #   rsh: sudo systemctl restart amma

      - run: sudo systemctl daemon-reload
      - run: sudo systemctl restart amma


